### 구글드라이브 연동



In [1]:
# # 구글드라이브 연동
# from google.colab import drive
# drive.mount('/gdrive', force_remount=True)

# # 구글 드라이브 파일 확인
# !ls '/gdrive/My Drive/temp/'

# # 반복되는 드라이브 경로 변수화
# drive_path = '/gdrive/My Drive/temp/'

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive
매수종목1.txt  example.docx	  ratings_small.txt  sample.xlsx
매수종목2.txt  height_weight.txt  sample1.pdf	     test.db.db
매수종목.csv   HelloWorld.xlsx	  sample2.pdf	     test.txt
demo.docx      little-char.png	  sample_merge.pdf


### 파이썬 머신러닝을 위한 모듈(라이브러리)


* 머신러닝 라이브러리
 * 사이킷런(Scikit-Learn)
* 행렬/선형대수/통계 라이브러리
  * **넘파이(NumPy): 고성능 과학계산을 위한 데이터 분석**(행렬, 선형대수)
  * 사이파이(SciPy): 자연과학, 통계
* 데이터 핸들링
 * 판다스(Pandas): 행과 열로 구성된 표 형식의 데이터(2차원 데이터 처리)
* 시각화
 * 맷플롯립(Matplotlib): 2D 그래프로 시각화
 * 시본(Seaborn): 다양한 색상 테마로 시각화

# Numpy (Numerical Python)
- 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
- 빠르고 효율적인 벡터 산술연산을 제공하는 n 차원 배열 (ndarray)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수 (sum(), sqrt(), mean())
- 선형대수, 난수 생성, 푸리에 변환

## Numpy 요약

In [ ]:
import numpy as np

In [ ]:
list = [1, 2, 10]
print(list * 3)

[1, 2, 10, 1, 2, 10, 1, 2, 10]


In [ ]:
arr = np.array(list)
print(arr * 3)

[ 3  6 30]


In [ ]:
# 2차원 리스트로부터 2차원 배열을 만드는 예
data = [[1,2,3],[4,5,6],[7,8,9]]
print(data)
type(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [ ]:
arr = np.array(data) # list를 ndarray로
print(arr)
type(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [ ]:
# 배열의 각 항목의 타입을 알아보려면 dtype 속성값을 보면 된다
arr.dtype

dtype('int64')

In [ ]:
# 배열의 구조를 보려면 shape 속성을 보면 된다
arr.shape

(3, 3)

In [ ]:
arr[1,2], arr[1][2]

(6, 6)

In [ ]:
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 초기값이 0인 배열을 만드는 법
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 레인지(범위)를 만드는 법
x = range(5)
print(type(x)) ; x

<class 'range'>


range(0, 5)

In [ ]:
# 레인지 형태로 배열을 만드는 법
y = np.arange(5)
print(type(y)) ; y

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [ ]:
x[2], y[2]

(2, 2)

In [ ]:
# 데이터의 타입을 변경하려면 astype을 사용한다
z = y.astype(np.float32) ; z

array([0., 1., 2., 3., 4.], dtype=float32)

In [ ]:
# 벡터화: 배열에 상수를 곱하거나 더할 수 있다
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
arr + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [ ]:
# 배열을 곱하면 각 항목별로 곱셈을 한다
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
# 전체는 ':'로 표시할 수 있다
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 0~11 값을 얻고 이를 4x3 배열로 재구성한다
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# 5 보다 큰 값을 모두 5로 교체하는 방법
data[data > 5] = 5
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
data.mean()

3.75

In [ ]:
data[0]

array([0, 1, 2])

In [ ]:
data[[0]]

array([[0, 1, 2]])

In [ ]:
data[[1,0]]

array([[3, 4, 5],
       [0, 1, 2]])

In [ ]:
# 행의 순서를 임의의 순으로 바꿀 수 있다
# 팬시 색인으로 배열을 바꾸면 본사본이 생기며 원래의 내용을 바지 않는다
data[[3,2,0,1]]

array([[5, 5, 5],
       [5, 5, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
data
# data 내용은 그대로 남아 있다

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# 행과 열을 모두 바꾸려면 아래와 같이 한다
data[[3,2,1,0]][:,[2,1,0]]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 4, 3],
       [2, 1, 0]])

In [ ]:
# 트랜스포즈는 행과 열의 위치를 바꾸는 것이다
data.T

array([[0, 3, 5, 5],
       [1, 4, 5, 5],
       [2, 5, 5, 5]])

In [ ]:
# 배열의 곱셈은 np.dot()을 사용한다
np.dot(data,data.T)

array([[ 5, 14, 15, 15],
       [14, 50, 60, 60],
       [15, 60, 75, 75],
       [15, 60, 75, 75]])

In [ ]:
# 각 행에 대해서 평균을 구한다 axis=1이면 행을 지칭한다
data.mean(axis=1)

array([1., 4., 5., 5.])

In [ ]:
# axis를 생략해도 된다
data.mean(1)

array([1., 4., 5., 5.])

In [ ]:
# 각 열에 대해서 평균을 구한다 axis=0이면 열을 지칭한다
data.mean(0)

array([3.25, 3.75, 4.25])

In [ ]:
# 불리언 연산, True는 1로 False는 0으로 숫자로 치환하여 계산가능하다
1 + True

2

In [ ]:
# 배열에서 값이 특정 수보다 큰 원소의 갯수를 반환한다.
x = np.array([1,2,3,4,5,6])
(x>4).sum()

2

In [ ]:
(data>1).sum()

10

In [ ]:
(x>4)

array([False, False, False, False,  True,  True])

In [ ]:
z = np.random.randint(0,100, 10) ; z

array([57, 33, 58, 93, 60, 66, 35, 73, 21, 85])

In [ ]:
z.sort() ; z

array([21, 33, 35, 57, 58, 60, 66, 73, 85, 93])

In [ ]:
t = np.array([[8,4,11,5],[2,10,7,3],[9,12,1,6]])
t

array([[ 8,  4, 11,  5],
       [ 2, 10,  7,  3],
       [ 9, 12,  1,  6]])

In [ ]:
# 열을 기준으로 소팅
t.sort(0) ; t

array([[ 2,  4,  1,  3],
       [ 8, 10,  7,  5],
       [ 9, 12, 11,  6]])

In [ ]:
# 행에서 소팅
t.sort(1) ; t

array([[ 1,  2,  3,  4],
       [ 5,  7,  8, 10],
       [ 6,  9, 11, 12]])

In [ ]:
t

array([[ 1,  2,  3,  4],
       [ 5,  7,  8, 10],
       [ 6,  9, 11, 12]])

In [ ]:
# 순서를 임의로 바꾸는 방법
z = np.arange(10) ; z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.permutation(z)

array([3, 2, 7, 5, 0, 9, 6, 1, 4, 8])

## Numpy 기초


In [ ]:
# Numpy 모듈(라이브러리)를 import하고 np 라는 이름으로 부르는 것이 관례
import numpy as np

numpy.ndarray

- 동일한 자료형을 가지는 값들이 배열 형태로 존재함
- N 차원 형태로 구성이 가능하다.
- 각 값들은 양의 정수로 색인(index)가 부여되어 있다.
- Numpy에서 차원(Dimension)을 rank, axis라고 부르기도 한다.
- ndarray를 줄여서 array로 표현한다.


In [ ]:
list = [1,2,3]
array1 = np.array(list)      # array생성하기: 1차원
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # 배열의 크기 확인

array2 = np.array([[1,2,3],
                   [2,3,4]]) # array생성하기: 2차원
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]]) # array생성하기: 2차원
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


ndarray.shape

해당 array의 크기를 알 수 있다.

- ndarray의 차원과 크기를 튜플(tuple) 형태로 출력

- shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.

- 위에서 array1.shape의 결과는 (3,) 으로써, 1차원의 데이터이며 총 3라는 크기를 갖고 있음을 알 수 있다.

- array2.shape의 결과는 (2,3) 으로써, 2차원의 데이터이며 2 * 3 크기를 갖고 있는 array 이다.


In [ ]:
# array 차원(Dimension) 확인
print('array1: {}차원, array2: {}차원, array3: {}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [ ]:
# array의 전체 요소 개수 확인
print(array1.size)
print(array2.size)

3
6


numpy에서 사용되는 자료형

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오프젝트 object
- 유니코드 unicode_


In [ ]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) # ndarray내의 데이터 타입 확인

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
# 서로 다른 데이터 타입을 갖을 때
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- 리스트와 다르게 ndarray는 같은 데이터 타입만 가능.
- 서로 다른 데이터 타입이 섞여 있을 경우 큰 데이터 타입으로 형 변환을 일괄 적용

In [ ]:
# 데이터 타입 변경하기
array_int = np.array([1,2,3])
print(array_int, array_int.dtype)
array_float = array_int.astype('float64')  # 데이터 타입 변경
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int64
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [ ]:
array_int = np.array([1.1, 2.1, 3.1], dtype=np.int64) # 타입 지정하여 생성
print(array_int, array_int.dtype)

[1 2 3] int64


In [ ]:
array_int = np.array([1.1, 2.1, 3.1], dtype='int64')
print(array_int, array_int.dtype)

[1 2 3] int64


#### Numpy 예제 01
Numpy를 이용해 다음과 같은 3차원 배열을 만들고 배열의 크기, 차원, 전체 요소 개수을 확인해보자 
```
array([[[1,2],
        [3,4]],
        
       [[5,6],
        [7,8]]])
```
```
배열의 크기: (2, 2, 2)
배열의 차원: 3
배열의 개수: 8
```


In [ ]:
arr = np.array([[[1,2],
                 [3,4]],
                [[5,6],
                 [7,8]]])
print("배열의 크기:", arr.shape)
print("배열의 차원:", arr.ndim)
print("배열의 개수:", arr.size)

배열의 크기: (2, 2, 2)
배열의 차원: 3
배열의 개수: 8


### ndarray 생성

In [ ]:
# 연속값으로 생성
seq_array = np.arange(10)  # range와 유사
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array = np.zeros((3,2), dtype='int32') # 0 으로 초기화
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))  # 1 로 초기화, dtype default
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [ ]:
full_array = np.full((5,5), 7) # 특정한 값으로 초기화
full_array

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
rand_array = np.random.rand(2,3) # 랜덤 값으로 초기화
rand_array

array([[0.4702363 , 0.11146557, 0.36651035],
       [0.76556191, 0.49744436, 0.37916044]])

In [ ]:
rand_array = np.random.randint(2,10) # 랜덤 값 범위지정
rand_array

4

In [ ]:
rand_array = np.random.randint(2,10, size=(2,3)) 
rand_array

array([[8, 8, 2],
       [3, 7, 5]])

#### Numpy 예제 02
1,2,3,....,50 이 담긴 배열을 생성하시오.

In [ ]:
seq_array = np.arange(1, 51)
seq_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### ndarray 차원과 크기 변경

In [ ]:
array1 = np.arange(10)
print("array1:\n", array1)

array2 = array1.reshape(2, 5)
print("array2:\n", array2)

array3 = array1.reshape(5, 2)
print("array3:\n", array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4, 3) # size 동일?

ValueError: ignored

In [ ]:
# 자동 변환(호환시)
array1 = np.arange(10)
print("array1:\n", array1)

array2 = array1.reshape(-1, 5)
print("array2:\n", array2)
print("array2 shape", array2.shape)

array3 = array1.reshape(5, -1)
print("array3:\n", array3)
print("array3 shape", array3.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape (2, 5)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape (5, 2)


In [ ]:
array1.reshape(-1, 4) # size 호환?

ValueError: ignored

In [ ]:
# ndarray 형태를 통일
# 원본 ndarray가 어떤 형태라도 2차원이고 1개의 컬럼을 갖는 ndarray로 변환
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print("array3d:\n", array3d.tolist())

array5 = array3d.reshape(-1, 1)   # 3차원을 2차원으로
print("array5:\n", array5.tolist())
print("array5 shape", array5.shape)

array6 = array1.reshape(-1, 1)   # 1차원을 2차원으로
print("array6:\n", array6.tolist())
print("array6 shape", array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape (8, 1)


### ndarray 인덱싱 & 슬라이싱
- 특정 데이터 추출
- 슬라이싱(Slicing) : 연속된 데이터 추출
- 팬시 인덱싱(Fancy Indexing) : 리스트 또는 ndarray 형태의 인덱싱 집합을 이용하여 여러 데이터를 추출
- 불린 인덱싱(Boolean Indexing) : True/False 값 인덱싱 집합을 이용하여 해당 인덱스 위치에 있는 데이터를 추출

In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array = np.arange(start=1, stop=10)
print("array:", array)
v = array[2]           # 0부터 시작
print("value:", v)
print(type(v))

array: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print("맨 뒤의 값:", array[-1], "맨 뒤에서 두 번째 값:", array[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
# 인덱스를 이용한 데이터 수정
array[0] = 9
array[8] = 0
array

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [ ]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
print()

print(array[0])
print()

print(array[0][0])
print(array[0,0])

[[1 2 3]
 [4 5 6]]

[1 2 3]

1
1


In [ ]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print(array2d)

print("(row=0, col=0) index 가리키는 값:", array2d[0, 0])
print("(row=0, col=1) index 가리키는 값:", array2d[0, 1])
print("(row=1, col=0) index 가리키는 값:", array2d[1, 0])
print("(row=2, col=2) index 가리키는 값:", array2d[2, 2])
# row 는 axis 0
# col 는 axis 1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


슬라이싱
- ':' 기호 앞에 시작 인덱스를 생략하면 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 맨 처음/마지막 인덱스로 간주



In [ ]:
# 1차원 슬라이싱
array = np.arange(1, 10)
print( array[0:3] )
print( array[:3] )
print( array[3:] )
print( array[:] )

[1 2 3]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 2차원 슬라이싱
array = np.arange(1, 10).reshape(3,3)
array

In [ ]:
array[0:2, 0:2]

In [ ]:
array[1:3, 0:3]

In [ ]:
array[1:3, :]

In [ ]:
array[:, :]

In [ ]:
array[:2, 1:]

In [ ]:
array[:2, 0]

In [ ]:
array[0]

array([1, 2, 3])

In [ ]:
array[1]

array([4, 5, 6])

In [ ]:
array[1].shape

(3,)

In [ ]:
# 팬시 인덱싱 1차원
array = np.arange(1, 10)
print(array)

array[[2,4,7]]

[1 2 3 4 5 6 7 8 9]


array([3, 5, 8])

In [ ]:
# 팬시 인덱싱 2차원
array = np.arange(1, 10).reshape(3,3)
print(array)

array[[0, 1], 2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 6])

In [ ]:
array[[0, 1], 0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
array[[0, 1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 불린 인덱싱
# 조건 필터링과 검색이 동시 가능
array = np.arange(1, 10)
array[ array > 5 ]

array([6, 7, 8, 9])

In [ ]:
# ndarray에 조건식 할당
array > 5  

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
bool_index = [False, False, False, False, False,  True,  True,  True,  True]
array[bool_index]

array([6, 7, 8, 9])

In [ ]:
# 불린 인덱싱 응용
name = np.array(['홍길동','박철수','이혜수','임유리','김영원'])
name_score = np.array([[60, 60],[70,70],[80,80],[90,90],[100,100]])
name_score

array([[ 60,  60],
       [ 70,  70],
       [ 80,  80],
       [ 90,  90],
       [100, 100]])

In [ ]:
name == '홍길동'

array([ True, False, False, False, False])

In [ ]:
name_score[name == '홍길동']

array([[60, 60]])

#### Numpy 예제 03 

BMI 구하기

10명에 대한 키와 몸무게가 들어있는 파일 ‘height_weight.txt’을 읽어 각 사람별 BMI 지수를 구하시오.
```
data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",") # delimiter : 구분자
data
```
  \\( BMI지수=\frac { 몸무게(kg) }{ 키(m) \times 키(m) } \\)
```
# 제곱 계산
# **2 or np.square()
```

In [ ]:
data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",") # delimiter : 구분자
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [ ]:
# BMI 구하기
height = data[0] / 100
weight = data[1]

BMI = weight / height**2
BMI

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

### 행렬의 정렬
- sort() : 정렬
- argsort() : 정렬된 행렬의 원본 행렬 원소에 대한 인덱스를 반환

In [ ]:
org_array = np.array([3,1,8,5])

sort_array = np.sort(org_array)
print("반환된 정렬 행렬:", sort_array)
print("원본행렬:", org_array)

반환된 정렬 행렬: [1 3 5 8]
원본행렬: [3 1 8 5]


In [ ]:
sort_array = org_array.sort()
print("반환된 정렬 행렬:", sort_array)
print("원본행렬:", org_array)

반환된 정렬 행렬: None
원본행렬: [1 3 5 8]


In [ ]:
np.sort(org_array)[::-1]  # 내림차순으로 정렬

array([8, 5, 3, 1])

In [ ]:
array = np.array([[8, 12],
                  [7, 1]])

sort_array = np.sort(array, axis=0) # row 방향으로 정렬
sort_array

array([[ 7,  1],
       [ 8, 12]])

In [ ]:
sort_array = np.sort(array, axis=1) # col 방향으로 정렬
sort_array

array([[ 8, 12],
       [ 1,  7]])

In [ ]:
# 정렬된 행렬의 인덱스 반환
org_array = np.array([3,1,8,5])
sort_index = np.argsort(org_array)
sort_index

array([1, 0, 3, 2])

In [ ]:
sort_index_desc = np.argsort(org_array)[::-1] # 내림차순
sort_index_desc

array([2, 3, 0, 1])

In [ ]:
# argsort() 활용 - 팬시 인덱스로 적용
name = np.array(['홍길동','박철수','이혜수','임유리','김영원'])
name_score = np.array([78, 95, 84, 98, 88])

sort_index_asc = np.argsort(name_score)
print("성적 오름차순 정렬 시 점수 인덱스:", sort_index_asc)
print("성적 오름차순으로 이름 출력:", name[sort_index_asc])

성적 오름차순 정렬 시 점수 인덱스: [0 2 4 1 3]
성적 오름차순으로 이름 출력: ['홍길동' '이혜수' '김영원' '박철수' '임유리']


### ndarray 연산
- 일반연산 : 산술연산, 비교연산 ...
- 선형대수 연산 : 행렬 내적과 전치 행렬

In [ ]:
array = np.array([1,2,3])
array + 100

array([101, 102, 103])

In [ ]:
array + array  # np.add(a, b)

array([2, 4, 6])

In [ ]:
array * array

array([1, 4, 9])

In [ ]:
array - array  # np.subtract(a, b)

array([0, 0, 0])

In [ ]:
array == array

array([ True,  True,  True])

In [ ]:
array > array

array([False, False, False])

In [ ]:
# 행렬 내적(행렬 곱)
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(a,b)
dot_product

array([[ 58,  64],
       [139, 154]])

In [ ]:
# 전치행렬 : 행과 열의 위치를 교환한 행렬
a = np.array([[1,2],
              [3,4]])
mat = np.transpose(a)
mat

array([[1, 3],
       [2, 4]])

### Universal 함수
- sin(), cos()다양한 수학함수를 제공
- 스칼라값을 입력으로 하는 math 패키지와 달리 배열에 대해 요소별로 적용

In [ ]:
array = np.arange(1, 11)
array.sum()  # np.sum(array)

55

In [ ]:
array.mean()  # np.mean(array)

5.5

In [ ]:
array = np.arange(5)
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
array = np.array([-1, -2, 3, 4, -5])
np.abs(array)

array([1, 2, 3, 4, 5])

#### Numpy 예제 04

영화평점 데이터 분석

In [15]:
import numpy as np

# 사용자 아이디, 영화 아이디, 평점, ?
data = np.loadtxt(drive_path + "ratings_small.txt", delimiter = "::", dtype = np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     1779,      2502,         4, 998699749],
       [     1779,      3160,         5, 977032398],
       [     1779,      3168,         4, 977033232]])

##### 데이터 분석하기
```
print(data.ndim)
print(data.shape)
print(data.size)
```

In [10]:
# 행(평점 작성개수) 1200004개 열(데이터의 종류) 4개
# 1200004 * 4 = 4800016
print(data.ndim)
print(data.shape)
print(data.size)

2
(300001, 4)
1200004


##### 전체 평점 평균 구하기
1. 평점 데이터만 추출 (인덱싱, 슬라이싱)
2. 평균 구하기 (mean)

In [16]:
# 전체 평점 평균 평점
rating_all_mean = data[:, 2].mean()
rating_all_mean

# 또는
rating_all_mean = np.mean(data[:, 2])
rating_all_mean

3.5613081289729034

##### 각 사용자별 평점 평균 구하기
1번 사용자의 평균 평점 구하기
1. 1번 사용자의 데이터만 Boolean Indexing 추출
2. 1번 사용자의 데이터에서 평점만 추출 (인덱싱, 슬라이싱)
3. 평균 구하기

참고
```
# 중복된 성분을 제외한 array를 반환
np.unique( ndarray )
```

In [18]:
user_id = np.unique(data[:,0])
user_id, user_id.shape

(array([   1,    2,    3, ..., 1777, 1778, 1779]), (1779,))

In [19]:
data[:, 0] == 1  # 1번 사용자

array([ True,  True,  True, ..., False, False, False])

In [ ]:
data[data[:,0] == 1]  # 1번 사용자 데이터만 색인

In [22]:
# 1번 사용자 평점 평균
user1 = data[data[:, 0] == 1]
user1_score = user1[:,2]
user1_mean = user1_score.mean()
user1_mean

4.188679245283019

In [23]:
# 또는

# 1번 사용자 평점 평균
data[data[:, 0] == 1][:,2].mean()

4.188679245283019

In [ ]:
# 각 사용자별 평점 평균
score = []
for i in user_id :
    user_score_mean = data[data[:, 0] == i][:,2].mean()
    score.append([i, user_score_mean])

score

##### 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기
- 리스트는 Boolean Indexing이 안되니 배열로 변환해야 인덱싱, 슬라이싱 가능

In [ ]:
# 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기
score_array = np.array(score) # ndarray로 변환

score_array[score_array[:, 1] >= 4][:, 0].astype('int')

##### CSV 파일로 저장
- np.savetxt() 이용

In [31]:
# csv 저장
np.savetxt(drive_path +'user_id_mean.csv', score, delimiter=', ', fmt="%.3f")