In [1]:
import sys
print(sys.argv)

['C:\\Users\\injoo\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\injoo\\AppData\\Roaming\\jupyter\\runtime\\kernel-4e2b8eef-ddf2-4546-9909-c50023009ebb.json']


In [3]:
sys.path

#경로 이름을 추가
#sys.path.append(r"C:\User\home\lib)

['C:\\Users\\injoo\\Documents\\ml',
 'C:\\Users\\injoo\\Anaconda3\\python37.zip',
 'C:\\Users\\injoo\\Anaconda3\\DLLs',
 'C:\\Users\\injoo\\Anaconda3\\lib',
 'C:\\Users\\injoo\\Anaconda3',
 '',
 'C:\\Users\\injoo\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\injoo\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\injoo\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\injoo\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\injoo\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\injoo\\.ipython']

In [5]:
#내 시스템의 환경 변수값을 알고 싶을 때
import os
os.environ['path']

'C:\\Users\\injoo\\Anaconda3;C:\\Users\\injoo\\Anaconda3\\Library\\mingw-w64\\bin;C:\\Users\\injoo\\Anaconda3\\Library\\usr\\bin;C:\\Users\\injoo\\Anaconda3\\Library\\bin;C:\\Users\\injoo\\Anaconda3\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Users\\injoo\\Anaconda3;C:\\Users\\injoo\\Anaconda3\\Library\\mingw-w64\\bin;C:\\Users\\injoo\\Anaconda3\\Library\\usr\\bin;C:\\Users\\injoo\\Anaconda3\\Library\\bin;C:\\Users\\injoo\\Anaconda3\\Scripts;C:\\Users\\injoo\\AppData\\Local\\Programs\\Python\\Python38-32\\Scripts\\;C:\\Users\\injoo\\AppData\\Local\\Programs\\Python\\Python38-32\\;C:\\Users\\injoo\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\injoo\\AppData\\Local\\atom\\bin'

In [7]:
os.getcwd() # %pwd

'C:\\Users\\injoo\\Documents\\ml'

In [13]:
# %ls
f= os.popen("dir")
print(f.read())

 C 드라이브의 볼륨: OS
 볼륨 일련 번호: 300A-F78A

 C:\Users\injoo\Documents\ml 디렉터리

2020-07-08  오후 12:15    <DIR>          .
2020-07-08  오후 12:15    <DIR>          ..
2020-07-08  오전 11:30    <DIR>          .ipynb_checkpoints
2020-07-07  오후 06:29             6,687 2020_07_07_파이썬과 데이터베이스 연동.ipynb
2020-07-08  오후 12:15             5,849 2020_07_08_파이썬_라이브러리_파일다루기.ipynb
2020-07-08  오전 11:29             7,518 2020_07_08_파이썬과 데이터베이스 연동.ipynb
               3개 파일              20,054 바이트
               3개 디렉터리  941,465,374,720 바이트 남음



In [15]:
os.chdir(r"c:/Apps/database/")
os.getcwd()

'c:\\Apps\\database'

In [17]:
os.chdir(r"C:\Users\injoo\Documents\ml")
os.getcwd()

'C:\\Users\\injoo\\Documents\\ml'

In [29]:
print(os.listdir())
os.mkdir("tmp")   #현재 있는 위치에 폴더를 만든다

['.ipynb_checkpoints', '2020_07_07_파이썬과 데이터베이스 연동.ipynb', '2020_07_08_파이썬_라이브러리_파일다루기.ipynb', '2020_07_08_파이썬과 데이터베이스 연동.ipynb']


In [30]:
#파일을 만들고 쓰기
print(os.listdir())
f = open("./tmp/test.text", mode = "wt", encoding="utf-8")
f.write("Hello Python")
f.close()

['.ipynb_checkpoints', '2020_07_07_파이썬과 데이터베이스 연동.ipynb', '2020_07_08_파이썬_라이브러리_파일다루기.ipynb', '2020_07_08_파이썬과 데이터베이스 연동.ipynb', 'tmp']


In [31]:
print(os.listdir("./tmp"))

['test.text']


In [32]:
#파일 이름 변경
os.rename("./tmp/test.text", "./tmp/hello.txt")
os.listdir("./tmp/")

['hello.txt']

In [34]:
#rmdir은 폴더 지우기인데, 폴더를 지우기 위해서는 안에 파일이 없어야한다
os.listdir("./tmp")
os.unlink("./tmp/hello.txt")
os.listdir("./tmp")
#os.rmdir("tmp")

[]

In [35]:
#폴더 지우기
os.rmdir("tmp")
os.listdir()

['.ipynb_checkpoints',
 '2020_07_07_파이썬과 데이터베이스 연동.ipynb',
 '2020_07_08_파이썬_라이브러리_파일다루기.ipynb',
 '2020_07_08_파이썬과 데이터베이스 연동.ipynb']

In [ ]:
#현 폴더 이하 트리 구조 출력
for folderName, subFolder, fileName in os.walk(r"c:/Apps/"):
    print(folderName)
    print(subFolder)
    print(fileName)

### Pickle
객체를 그대로 저장하는 모듈

In [41]:
#딕셔너리 객체를 저장
import pickle

f = open(r"c:/Apps/test.txt", mode = "wb")
data = {1: "python", 2: "Java", 3:"c"}
pickle.dump(data, f)
f.close()

In [42]:
with open(r"c:/Apps/test.txt", "rb") as f:
    print(pickle.load(f))

{1: 'python', 2: 'Java', 3: 'c'}


### shelve

In [44]:
import shelve
data1 = ["aaa", 22, 33]
data2 = ["bbb", 11, 44]

with shelve.open(r"c:/Apps/test1.bin") as f:
    f['d1'] = data1
    f['d2'] = data2


In [45]:
with shelve.open(r"c:/Apps/test1.bin") as f:
    print(f['d1'])

['aaa', 22, 33]


### OpenPyXL
Excel을 읽고 쓰는 모듈

In [48]:
import openpyxl

wb = openpyxl.Workbook()
sheet = wb.active
sheet['A1'] = "Hello"
wb.save(r"c:/Apps/Hello.xlsx")

In [50]:
wb = openpyxl.load_workbook(r"c:/Apps/Hello.xlsx")
print(wb.sheetnames)

sheet = wb.active
print(sheet.title)

['Sheet']
Sheet


In [54]:
sheet_last = wb.create_sheet("newSheet")
sheet_first =  wb.create_sheet("firstSheet", 0)
sheet = wb['newSheet']

wb.save(r"c:/Apps/Hello.xlsx")

In [55]:
sheet['A1'] = "안녕하세요~"

print(sheet['A1'].value)

안녕하세요~


In [56]:
sheet.cell(row=2, column=2).value = 'Python is fun'


In [60]:
import openpyxl
import pandas as pd

wb = openpyxl.load_workbook(r"c:/Apps/temp/sample.xlsx")
sheet = wb.active

df = pd.DataFrame(sheet.values)
df

0   1   2
0   이름  나이  성별
1  홍길동  30   남
2  박철수  25   남
3  이혜수  33   여
4  임유리  24   여
5  김영원  43   남

In [61]:
df.columns = df.iloc[0, :]
df = df.iloc[1:, :]
df

0   이름  나이 성별
1  홍길동  30  남
2  박철수  25  남
3  이혜수  33  여
4  임유리  24  여
5  김영원  43  남

## python-docs

In [64]:
#pip install python-docx
import docx

doc = docx.Document()
doc.save(r"c:/Apps/example.docx")

In [66]:
para = doc.add_paragraph()
run = para.add_run("안녕하세요")
run.bold = True
run.font.size = docx.shared.Pt(20)

doc.save(r"c:/Apps/example.docx")

In [67]:
from PyPDF2 import PdfFileReader, PdfFileWriter

path = r"c:/Apps/temp/sample1.pdf"

pdf = PdfFileReader(open(path, 'rb'))
docinfo = pdf.getDocumentInfo()
docinfo

{'/Producer': 'FPDF 1.7', '/CreationDate': 'D:20200630103238'}

In [68]:
pdf.getNumPages()

1

# Numpy

In [69]:
import numpy as np
np.__version__

'1.18.1'

In [2]:
# ndarray
import numpy as np
list = [1,2,3]

array1 = np.array(list) #Array화 시키는 것 
print(array1)
print(array1.shape)
print(array1.ndim)
print(array1.size)

array2 = np.array([[1,2,3],
                   [2,3,4]])

print(array2.shape)
print(array2.ndim)
print(array2.size)

[1 2 3]
(3,)
1
3
(2, 3)
2
6


In [81]:
# ndarray type
array2.dtype

array3 = np.array([1,2,3.0])



dtype('float64')

In [85]:
# ndarray type 변경
array_int = np.array([1,2,3])
array_int.dtype

array_float = array_int.astype('float64')
array_float.dtype

dtype('float64')

In [89]:
array_float1 = np.array([1,1, 2.1, 3.1], dtype = np.int64)
array_float1

array([1, 1, 2, 3], dtype=int64)

### 연습 01

In [91]:
array = np.array([[[1,2],
                    [3,4]],
       
                    [[5,6],
                    [7,8]]])

print(array.shape)
print(array.ndim)
print(array.size)

(2, 2, 2)
3
8


In [3]:
# ndarray 생성
seq_array = np.arange(10)
print(seq_array.shape)
print(seq_array)

(10,)
[0 1 2 3 4 5 6 7 8 9]


In [96]:
zero_array = np.zeros( (3,2), dtype='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [98]:
one_array = np.ones((3,2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [99]:
full_array = np.full((5,5), 2)
full_array

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [101]:
rand_array = np.random.rand(2,3)
rand_array

array([[0.33653262, 0.03426592, 0.09741362],
       [0.014397  , 0.26509538, 0.31476815]])

In [102]:
rand_array = np.random.randint(2, 10, size=(2,3))
rand_array

array([[5, 2, 7],
       [4, 5, 8]])

### 연습 02

In [106]:
array = np.arange(1,51)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [114]:
# ndarray 차원(모양) 변경
array1 = np.arange(10)
array1

array2 = array1.reshape(2,5)

array3 =array1.reshape(5,2)
array3

# -1을 넣는 것은 부분적으로 자동으로 해주는 것이다
array4= array1.reshape(2, -1)
print(array4)

array5 = array1.reshape(5, -1)
print(array5)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
array3d
print(array3d)
print()
array3d.tolist()

array5 = array3d.reshape(-1,1)
array5.ndim

array6 = array1.reshape(-1, 1) #1차원 배열을 reshape해도 2차원 배열이된다
print(array6)
array6.ndim

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


2

In [132]:
#인덱싱 & 슬라이싱 (팬시인덱싱, 불린인덱싱)
array = np.arange(start=1, stop=10)
v = array[2] #인덱싱
v



3

In [6]:
array = np.array([[1,2,3], [4,5,6]])
print(array)

array[0]
array[0][0]
print(array[0,1])  #특이하네
print(array[0][1])

[[1 2 3]
 [4 5 6]]
2
2


In [136]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print(array2d)

array2d[2,2]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [137]:
array = np.arange(1, 10)
print(array)
array[3:]

[1 2 3 4 5 6 7 8 9]


array([4, 5, 6, 7, 8, 9])

In [144]:
array = np.arange(1,10).reshape(3,3)
print(array)

array[0:2, 0:2]  #특이하네, row 와 column도 범위 지정 가능
array[1:3, 0:3]
array[1:3, :]
array[:, :]
array[:2, 1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [145]:
#팬시 인덱싱
array = np.arange(1, 10)
print(array)

array[ [2,4,7]]

[1 2 3 4 5 6 7 8 9]


array([3, 5, 8])

In [10]:
array = np.arange(1, 10).reshape(3,3)
print(array)
print(array[[0,1], 2])  #콤마를 기준으로 이전은 행, 이후는 열. 0번째와 1번째 행을 가져오고 2번째 열을 가져와라
print(array[[0,1], 0:2])
print(array[[0,1]])  #행만 지정했으니 열은 전체 #주의 == print(array[[0,1], :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [150]:
#불린 인덱싱
array = np.arange(1,10)
array[array>5]

array([6, 7, 8, 9])

In [153]:
name = np.array(['홍길동', '박철수', '이혜수', '임유리', '김영원'])
name_score = np.array([[60,60], [70,70], [80,80], [90,90], [100, 100]])

print(name_score)
name_score[name=='홍길동']

[[ 60  60]
 [ 70  70]
 [ 80  80]
 [ 90  90]
 [100 100]]


array([[60, 60]])

### 예제 3 BMI 지수 구하기

BMI = 몸무게 / 키*키

In [197]:
drive_path = r"C:/Apps/temp/"
data = np.loadtxt(drive_path+"height_weight.txt", delimiter=",") #delimiter = 구분자

h = data[0]/100
w = data[1]

BMI = w / h**2
BMI

# bmi = [None]*10
# for i in range(10):
#     h = data[0][i]
#     w = data[1][i]
#     bmi[i] = w/h**2

# bmi
    

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [198]:
#정렬
org_array = np.array([3,5,2,1,9])
sort_array = np.sort(org_array)
sort_array

org_array.sort()

In [199]:
np.sort(org_array)[::-1] #내림차순

array([9, 5, 3, 2, 1])

In [201]:
#numpy 정렬하기
array = np.array([[8, 12], 
                 [7,1]])

sort_array = np.sort(array, axis = 0)  #column 방향으로 정렬된다
sort_array

array([[ 7,  1],
       [ 8, 12]])

In [202]:
sort_array = np.sort(array, axis = 1)  #row 방향으로 정렬된다
sort_array

array([[ 8, 12],
       [ 1,  7]])

In [205]:
org_array = np.array([3,5,2,1,9])
sort_array = np.sort(org_array)
sort_index = np.argsort(org_array)  #array한 것의 Index? 서로 다른 두 array가 있을때 연결
print(sort_array)
print(sort_index)     #정렬되었을 때의 인덱스를 나타낸다, index sort

[1 2 3 5 9]
[3 2 0 1 4]


In [12]:
#argsort 활용
name = np.array(['홍길동', '박철수', '이혜수', '이유리', '김영원'])
name_score = np.array([78, 95, 84, 98, 88])

#정렬되었을 때의 인덱스를 반환하니, 그 인덱스를 원래 자료에 넣으면 그 정렬된 순서대로 출력될 것이다.
sort_index = np.argsort(name_score)
print(sort_index)
name[sort_index]

[0 2 4 1 3]


array(['홍길동', '이혜수', '김영원', '박철수', '이유리'], dtype='<U3')

In [ ]:
# ndarray 연산
